//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HospitalApiSA.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Hospital
    {
        public int HospitalID { get; set; }
        public Nullable<int> CityID { get; set; }
        public string HospitalName { get; set; }
        public string MapURL { get; set; }
        public Nullable<int> Status { get; set; }
    
        public virtual City City { get; set; }
    }
}
